language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
script: bundle exec rspec
notifications:
  email:
    - wpscanteam@gmail.com
matrix:
  allow_failures:
    - rvm: 1.9.2
